# tpws: базовая стратегия для слабых роутеров (64 MB RAM)
MODE=tpws
PORT=987
ARGS="--split-pos=1 --disorder --oob --hostcase --tlsrec=sni --mss=128 --hostlist=/opt/etc/zapret/lists/list-general.txt --hostlist=/opt/etc/zapret/lists/list-google.txt --hostlist-exclude=/opt/etc/zapret/lists/list-exclude.txt"
