# nfqws: базовая стратегия (NFQUEUE)
# ВНИМАНИЕ: конфликтует с HW offload. Использовать только на мощных ASUS.
MODE=nfqws
QNUM=200
ARGS=--dpi-desync=fake,split2 --dpi-desync-ttl=2 --dpi-desync-fake-tls=/opt/etc/zapret/fake/tls_clienthello_www_google_com.bin --dpi-desync-fake-quic=/opt/etc/zapret/fake/quic_initial_www_google_com.bin
